version: '3'

services:

  marketplace-ui-service:
    image: marketplace-ui-service:0.0.1-SNAPSHOT
    build:
      context: ./ui-web
    container_name: marketplace_ui_service
    environment:
      SERVICES_SERVER_API: http://marketplace-server-service:8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marketplace
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
      RECAPTCHA_SITEKEY: ${RECAPTCHA_SITEKEY}
    depends_on:
      - marketplace-server-service
      - db
    ports:
      - "8089:8089"

  marketplace-server-service:
    image: marketplace-server-service:0.0.1-SNAPSHOT
    build:
      context: ./server-api
    container_name: marketplace_server_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marketplace
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      CUSTOM_SECURITY_JWT_SECRET: ${JWT_SECRET}
      CUSTOM_SECURITY_ADMINS_ADMINTEST_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: marketplace_db
    restart: always
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local