spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
    group:
      dev:
        - local-dev
        - debug
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/marketplace
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB

server:
  error:
    include-message: always
    include-binding-errors: always

custom:
  security:
    jwt:
      secret: eitu9aichae7eitee9XiciweishohW3pieshaifasosai5xie9Oomobulohyu8iT
      access-expire-in: 10m
      refresh-expire-in: 3d
    admins:
      admintest:
        email: admintest@gmail.com
        password: fua9eeF1ahphooy5eth9ooth1iebee0AeWahyob4lai4cha3goohaewoh0gicieB

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: when_authorized